// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/aql-lang/aql/eng/go"
	sdk "github.com/voxgig-sdk/ipinfo-developer-sdk/go"
)

// registerSDKWords installs three native AQL words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word.
func registerSDKWords(r *eng.Registry, client *sdk.IpinfoDeveloperSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.NativeSig{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		dual := eng.NativeSig{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:        op,
			ForwardArgs: true,
			Signatures:  []eng.NativeSig{single, dual},
		})
	}
}

func runOp(client *sdk.IpinfoDeveloperSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.IpinfoDeveloperSDK, name string) (sdk.IpinfoDeveloperEntity, error) {
	switch strings.ToLower(name) {
	case "abuse":
		return client.Abuse(nil), nil
	case "asn":
		return client.Asn(nil), nil
	case "carrier":
		return client.Carrier(nil), nil
	case "company":
		return client.Company(nil), nil
	case "core":
		return client.Core(nil), nil
	case "domain":
		return client.Domain(nil), nil
	case "general":
		return client.General(nil), nil
	case "get_current_information":
		return client.GetCurrentInformation(nil), nil
	case "get_information_by_ip":
		return client.GetInformationByIp(nil), nil
	case "ipinfo_core":
		return client.IpinfoCore(nil), nil
	case "ipinfo_lite":
		return client.IpinfoLite(nil), nil
	case "ipinfo_plus":
		return client.IpinfoPlus(nil), nil
	case "lite":
		return client.Lite(nil), nil
	case "max":
		return client.Max(nil), nil
	case "men":
		return client.Men(nil), nil
	case "place":
		return client.Place(nil), nil
	case "plus":
		return client.Plus(nil), nil
	case "privacy":
		return client.Privacy(nil), nil
	case "privacy_extended":
		return client.PrivacyExtended(nil), nil
	case "range":
		return client.Range(nil), nil
	case "residential_proxy":
		return client.ResidentialProxy(nil), nil
	case "single":
		return client.Single(nil), nil
	case "whois_asn":
		return client.WhoisAsn(nil), nil
	case "whois_domain":
		return client.WhoisDomain(nil), nil
	case "whois_ip":
		return client.WhoisIp(nil), nil
	case "whois_net_id":
		return client.WhoisNetId(nil), nil
	case "whois_org":
		return client.WhoisOrg(nil), nil
	case "whois_poc":
		return client.WhoisPoc(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts an AQL Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.VType.Matches(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.VType.Matches(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.VType)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
