// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/ipinfo-developer-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"abuse | asn | carrier | company | core | domain | general | get_current_information | get_information_by_ip | ipinfo_core | ipinfo_lite | ipinfo_plus | lite | max | men | place | plus | privacy | privacy_extended | range | residential_proxy | single | whois_asn | whois_domain | whois_ip | whois_net_id | whois_org | whois_poc"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.IpinfoDeveloperSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "ipinfo-developer_list",
		Description: "List records from IpinfoDeveloper. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "ipinfo-developer_load",
		Description: "Load a single record from IpinfoDeveloper. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.IpinfoDeveloperSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.IpinfoDeveloperSDK, name string) (sdk.IpinfoDeveloperEntity, error) {
	switch strings.ToLower(name) {
	case "abuse":
		return client.Abuse(nil), nil
	case "asn":
		return client.Asn(nil), nil
	case "carrier":
		return client.Carrier(nil), nil
	case "company":
		return client.Company(nil), nil
	case "core":
		return client.Core(nil), nil
	case "domain":
		return client.Domain(nil), nil
	case "general":
		return client.General(nil), nil
	case "get_current_information":
		return client.GetCurrentInformation(nil), nil
	case "get_information_by_ip":
		return client.GetInformationByIp(nil), nil
	case "ipinfo_core":
		return client.IpinfoCore(nil), nil
	case "ipinfo_lite":
		return client.IpinfoLite(nil), nil
	case "ipinfo_plus":
		return client.IpinfoPlus(nil), nil
	case "lite":
		return client.Lite(nil), nil
	case "max":
		return client.Max(nil), nil
	case "men":
		return client.Men(nil), nil
	case "place":
		return client.Place(nil), nil
	case "plus":
		return client.Plus(nil), nil
	case "privacy":
		return client.Privacy(nil), nil
	case "privacy_extended":
		return client.PrivacyExtended(nil), nil
	case "range":
		return client.Range(nil), nil
	case "residential_proxy":
		return client.ResidentialProxy(nil), nil
	case "single":
		return client.Single(nil), nil
	case "whois_asn":
		return client.WhoisAsn(nil), nil
	case "whois_domain":
		return client.WhoisDomain(nil), nil
	case "whois_ip":
		return client.WhoisIp(nil), nil
	case "whois_net_id":
		return client.WhoisNetId(nil), nil
	case "whois_org":
		return client.WhoisOrg(nil), nil
	case "whois_poc":
		return client.WhoisPoc(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
